# Generated by Django 5.0.7 on 2024-07-18 06:25

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("VIEWER", "بازدیدکننده"), ("BLOGGER", "وبلاگ\u200cنویس")],
                default="VIEWER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "این نام کاربری قبلا ثبت شده است."},
                help_text="کاراکترهای مجاز: حروف انگلیسی، اعداد و @/./+/-/_",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
