# Generated by Django 5.0.7 on 2024-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
