# Generated by Django 5.0.7 on 2025-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_receive_email_user_receive_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                error_messages={"unique": "اکانت دیگری با این شماره وجود دارد."},
                max_length=30,
                unique=True,
            ),
        ),
    ]
