# Generated by Django 5.0.7 on 2025-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_is_admin_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_description",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
