# Generated by Django 5.0.7 on 2024-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_level_level_num_alter_price_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="price",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="type",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
