# Generated by Django 5.0.7 on 2024-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_level_is_available_price_is_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
