# Generated by Django 5.0.7 on 2024-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_order_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.IntegerField(null=True),
        ),
    ]
