# Generated by Django 5.0.7 on 2024-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_price_alter_order_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در حال بررسی"),
                    ("ACCEPTED", "پذیرفته شده"),
                    ("DOING", "در حال انجام"),
                    ("FINISHED", "به اتمام رسیده"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
