# Generated by Django 5.0.7 on 2024-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("در حال بررسی", "در حال بررسی"),
                    ("پذیرفته شده", "پذیرفته شده"),
                    ("در حال انجام", "در حال انجام"),
                    ("به اتمام رسیده", "به اتمام رسیده"),
                    ("رد شده", "رد شده"),
                ],
                default="در حال بررسی",
                max_length=20,
            ),
        ),
    ]
