# Generated by Django 5.0.7 on 2024-09-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("change_order_status", "Can change the status of orders")
                ]
            },
        ),
    ]
