# Generated by Django 5.0.7 on 2025-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_price_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(max_length=300, null=True),
        ),
    ]
