# Generated by Django 5.0.7 on 2025-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_order_ordered_by_admin_alter_order_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="buyer",
            new_name="customer",
        ),
    ]
